# @package _global_

defaults:
  - _self_
  - trainer: default.yaml
  - model: default.yaml
  - data: trainid.yaml
  - synth: h2of.yaml
  - loss: switch_spec.yaml
  - fx: null
  - experiment: null
  - exp: null
  - optuna: null

# name of stat to use as monitor 
# ex.) "val_0/lsd" - LSD of 0th validation dataset
name: null
sample_rate: 16000
monitor: "val_1/lsd"
checkpoint_every: 50
seed: 0
ckpt: null
sep_fx: false
ext_f0: false
id_base: null

hydra:
  run:
    dir: logs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/${name}/multirun_${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}